// <auto-generated />
using System;
using DemoVisitorInfoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoVisitorInfoApp.Migrations
{
    [DbContext(typeof(VisitContext))]
    [Migration("20240910124110_UpdateVisitFieldTypes")]
    partial class UpdateVisitFieldTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoVisitorInfoApp.Data.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cookies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("LastPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LastQueryString")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LastReferrerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("LastVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ReferrerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ScreenResolution")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
